import React, { Component } from "react";
import { Link } from "react-router-dom";

class CoinInfo extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  render() {
    return (
      <main className="componentContainer">
        <section className="description">
          <h3 className="coin_desc-title">
            You have successfully created your very own Test Wallet
          </h3>
          <p className="coin_desc-para">
            Congratulations! Now that your test wallet has been created and you
            know what each piece is and how they work, you are now ready to do
            some test transactions to get you familiar with the process. You
            will recieve testcoins generated by the Cryptorial, and they will
            allow you to purchase a fake bitcoin, which you will then sell back
            to Cryptorial, so you can see the procedure in action.
          </p>
          <h3 className="coin_desc-sub">Crypto Coins</h3>
          <p className="coin_desc-para">
            Before you start practicing with the transactions, here is some
            information on the more popular coins on the market. There are
            thousands of different coins out there, but most of them are worth
            mere cents, while some of these more popular ones, like Bitcoin,
            reached $17,900 USD in December of 2017.
          </p>
          <Link
            className="buttonBackwards"
            onClick={this.props.pageBackwards}
            to={"/publickey"}
          >
            Previous
          </Link>
        </section>

        <section className="component">
          <div className="coin">
            <h3 className="coin_title">Popular Digital Assets</h3>
            <div className="coin_desc">
              <div className="btc_desc">
                <h3>Bitcoin</h3>
                <p>Current Price: </p>
                <p>desc.</p>
              </div>
              <div className="eth_desc">
                <h3>Ethereum</h3>
                <p>Current Price: </p>
                <p>desc.</p>
              </div>
              <div className="doge_desc">
                <h3>Dogecoin</h3>
                <p>Current Price: </p>
                <p>desc.</p>
              </div>
              <div className="ltc_desc">
                <h3>Litecoin</h3>
                <p>Current Price: </p>
                <p>desc.</p>
              </div>
            </div>
            <Link
              className="buttonForwards"
              onClick={this.props.pageForwards}
              to={"/samplebuy"}
            >
              Next
            </Link>
          </div>
        </section>
      </main>
    );
  }
}

export default CoinInfo;
