import React, { Component } from 'react';
import { Link } from 'react-router-dom';

class TestWallet extends Component {
  render() {
    return (
      <section className="noDescription test-wallet">
        <h3>You have successfully created your very own Test Wallet</h3>
        <p>
          Congratulations! Now that your test wallet has been created and you
          know what each piece is and how they work, you are now ready to do
          some test transactions to get you familiar with the process. You will
          recieve testcoins generated by the Cryptorial, and they will allow you
          to purchase a fake bitcoin, which you will then sell back to
          Cryptorial, so you can see the procedure in action.
        </p>
        <button>
          <Link to={'/privatekey'}>Previous</Link>
        </button>
        <button>
          <Link to={'/coininfo'}>Next</Link>
        </button>
      </section>
    );
  }
}

export default TestWallet;
